---
#
# Main office applications
#

- name: Install office applications
  action: apt pkg={{ item }} state=installed force=yes
  with_items:
    - xclip
    - pdfshuffler
    - xchm                      # Read microsoft help files
    - okular                    # PDF reader of choice
    - inkscape
    - krita                     # Photo editing
    - gimp
    #- gthumb                    # Picture viewer & basic editor
    - keepassx
    - gwakeonlan                # Turn computers on around the office
    - ktorrent
    - wireshark
    - gparted
    #- audacity
    - audacity                  # Modify mp3 or wave files
    - filezilla
    - chromium
    - wine
    - simple-scan               # Self configures usb scanners
    - gkrellm                   # System stats program
    - backintime-gnome          # Backup 
    - fsarchiver                # Backup system tool
    - file-roller               # Better integration with nautilus
    - cheese                    # camera shot
    - firefox-esr
    - icedove
      
- name: Install compression tools
  action: apt pkg={{ item }} state=installed force=yes
  with_items:
    - unzip
    - unrar
    - zip
    - p7zip
    - gzip
    - pbzip2
    - bzip2
    - mscompress
    - xz-utils
    - dar

- name: Install flash
  apt: pkg=flashplugin-nonfree
  when: ansible_os_family == "Debian"

- include: common/tasks/x2go.yml      
- include: common/tasks/virtual-box.yml
