---
#
# System related tasks and tools
#

- name: Install system tools
  action: apt pkg={{ item }} state=installed force=yes
  with_items:
    - htop
    - pwgen
    - screen
    - openssh-server
    - sysstat
    - ncdu              # Check disk usage per directory
    - mosh              # Awesome mobile ssh server/client
    - safe-rm           # Stop people typing 'rm -fr /'
    - molly-guard       # Save people from rebooting the wrong server.
    - expect            # Required for some installation scripts
    - mg                # emacs lite
    - pulseaudio-module-bluetooth # allows bluetooth connection via cmd line
    - git
    - firmware-linux-nonfree

- name: Update command-not-found
  action: command update-command-not-found creates=/var/cache/apt/apt-file
  when: ansible_os_family == "Debian"

  # Move the following
  
    # Source building tools
    # - build-essential   # Build tools like gcc.
    
    # Zsh (& oh-my-shell)
    # - zsh

    # Debian package helpers
    # - command-not-found # Package suggestion utility

    # Monitoring tools
    # - nethogs
    # - bwm-ng            # bandwidth monitor for network & disk

    # Firmware
    # - firmware-linux-nonfree
